### ISSUE TITLE
kmonad won't accept non-qwerty layout as defsrc

### ISSUE THREAD

**Issue by RJDan** [kmonad/kmonad-contrib#9]
Hello
I am trying to set Dvorak as the defsrc for my laptop. Kmonad won't accept any of the non-qwerty keys as defsrc.
If I try to add this as the defsrc I get errors about an unexpected symbol.
```(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12      del  pause  ssrq home
  grv   &   2    3    4    5    6    7    8    9    0    -    =    bspc   nlck kp/  kp*  kp-
  tab   ;    ,       .      p      y    f    g       c      r      l     /      @       \      kp7  kp8  kp9  kp+
  caps a   o    e     u      i     d    h       t      n     s    -      ret                        kp4  kp5  kp6
  lsft   "   q      j     k     x     b    m     w      v    z   rsft                 up         kp1  kp2  kp3  kprt
  lctl  lmet   lalt           spc            ralt    rctl    left down rght     kp0  kp.
  )
```
I replaced each of the problem symbols one-by-one. They were all the symbols not found on the defsrc map for qwerty.

So ... ```& @ " ```
It is even worse for programer Dvorak where the 'number row' in almost entirely symbols not on the defsrc qwerty map.

Am I doing  something wrong with my map?

My keyboard is Qwerty but I have changed the default map to Dvorak (both Sway and Gnome), so I would like kmonad to assume dvorak rather that Qwerty.

**Comment by slotThe** [comment]
The `defsrc` should be the physical layout of your keys; i.e., probably some form of US international. Its the `deflayer`s where you can specify your actual keybord layout

**Comment by RJDan** [comment]
Thanks for the quick reply.

I am using Kmonad for the features that I can't setup with xkbd (like multiple layers, remapping the f-keys). So the kmonad layout is a modified Dvorak.

My issue is that I have Dvorak set as the default keyboard layout on my installation (I touch type with Dvorak and using qwerty is painfully slow). I need to have Dvorak as the default so that if something breaks and kmonad doesn't work, or if I use the tty from another account I don't have to try to type qwerty (which slows me down a lot).

Kmonad registers that the keystrokes come from a Dvorak keyboard so that works.
But I cant have Qwerty as the defsrc because it doesn't match the map I want.

**Comment by RJDan** [comment]
So   physical keyboard (Qwerty) ---- [system settings change ] ----- Dvorak ------ [Kmonad] -------- Dvorak + extra functions

**Comment by slotThe** [comment]
> I need to have Dvorak as the default so that if something breaks and kmonad doesn't work,

I mean, worst-case you will have to open a terminal, and type in

    setxkbmap -layout us -variant dvorak

I'm also not good at QWERTY, but I think that that's manageable :)

> or if I use the tty from another account I don't have to try to type qwerty (which slows me down a lot).

KMonad does work in the TTY, even if you log into another user (though I would imagine this use-case is quite rare.).

**Comment by RJDan** [comment]
> I mean, worst-case you will have to open a terminal, and type in setxkbmap -layout us -variant dvorak I'm also not good at QWERTY, but I think that that's manageable :)

Right, so you are saying I should have Qwerty as the default and change to Dvorak on the terminal when kmonad doesn't/won't start?
I will do this then....

So there is no way to set non-qwerty symbols as the defsrc?

**Comment by slotThe** [comment]
> Right, so you are saying I should have Qwerty as the default and change to Dvorak on the terminal when kmonad doesn't/won't start?

Yes. But, speaking from experience, KMonad *will* start, so don't worry too much about it :). Alternatively, the [Emacs integration](https://github.com/kmonad/kbd-mode) also has a demo mode feature, which may come in handy.

> So there is no way to set non-qwerty symbols as the defsrc?

Not necessarily non-qwerty, but KMonad's internal key representation is relatively close to Linux kernel keycodes, and thus treats certain things as not being actual keys, but shifted versions of other keys. It's those that can't be used in the `defsrc`.
